--- 
default: 
  image: "alpine:latest"
build: 
  before_script: 
    - "npm install"
  script: 
    - "echo \"Building deploy package\""
    - "echo \"Build successful\""
  stage: build
  tags: 
    - testing
    - development
stages: 
  - build

# --- 
# build: 
#   before_script: 
#     - "npm install"
#   cache: 
#     paths: 
#       - node_modules/
#   install_dependencies: 
#     artifacts: 
#       paths: 
#         - node_modules/
#     script: 
#       - "npm install"
#     stage: build
#   script: 
#     - "echo \"Building deploy package\""
#     - "echo \"Build successful\""
#   stage: build
#   stages: 
#     - build
#   tags: 
#     - testing
#     - development
# default: 
#   image: "alpine:latest"
# stages: 
#   - build
