stages:
    - build
build:
    stage: build
    tags: 
        - testing
        - development
    script:
        - echo "Building deploy package"
        - echo "Build successful"


# image: alpine:latest

#     stages:
#       - build

#     cache:
#       paths:
#         - node_modules/

#     install_dependencies:
#       stage: build
#       script:
#         - npm install
#       artifacts:
#         paths:
#           - node_modules/
# default:
#   image: alpine:latest

# test:
#   script:
#   - npm install