# --- 
# default: 
#   image: node:latest
#   # image: "alpine:latest"
# build: 
#   before_script: 
#     - "npm install"
#   script: 
#     - "echo \"Building deploy package\""
#     - "echo \"Build successful\""
#   stage: build
#   tags: 
#     - testing
#     - development
# stages: 
#   - build

# --- 
# build: 
#   before_script: 
#     - "npm install"
#   cache: 
#     paths: 
#       - node_modules/
#   install_dependencies: 
#     artifacts: 
#       paths: 
#         - node_modules/
#     script: 
#       - "npm install"
#     stage: build
#   script: 
#     - "echo \"Building deploy package\""
#     - "echo \"Build successful\""
#   stage: build
#   stages: 
#     - build
#   tags: 
#     - testing
#     - development
# default: 
#   image: "alpine:latest"
# stages: 
#   - build


--- 
build: 
  script: 
    - "npm install"
    - "npm run-script build"
  stage: build
  tags: 
    - testing
    - development
cache: 
  paths: 
    - node_modules/
default: 
  image: "node:latest"
deploy: 
  script: 
    - "npm run-script deploy"
  stage: deploy
stages: 
  - build
  - deploy
